# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/falnama-dev',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/falnama-dev',
                'lib_path': 'falnama_dev'},
  'syms': {'falnama_dev.core': {'falnama_dev.core.foo': ('core.html#foo', 'falnama_dev/core.py')}}}
