"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/explorations/00_core.ipynb.

# %% auto 0
__all__ = ['bar']

# %% ../nbs/explorations/00_core.ipynb 3
def bar(): pass
