"""Answer: `import fairdatanow`"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/10_how-to-make-sense-of-8118-files.ipynb.

# %% auto 0
__all__ = []

# %% ../notebooks/10_how-to-make-sense-of-8118-files.ipynb 16
pass
